# Generated by Django 4.2.7 on 2023-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="users", name="django_user",),
        migrations.RemoveField(model_name="users", name="id",),
        migrations.RemoveField(model_name="users", name="name",),
        migrations.RemoveField(model_name="users", name="phone",),
        migrations.AddField(
            model_name="users",
            name="password",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="username",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="users", name="email", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="users",
            name="userid",
            field=models.AutoField(
                default=0, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterModelTable(name="users", table="users",),
    ]
