# Generated by Django 4.2.7 on 2023-12-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_users_django_user_remove_users_id_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="users", table=None,),
    ]
