# Generated by Django 4.2.7 on 2023-12-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_users_groups_remove_users_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="users", table=None,),
    ]
