# Generated by Django 4.1.2 on 2023-12-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_users_table"),
        ("users", "0005_alter_users_table"),
    ]

    operations = []
