# Generated by Django 4.2.7 on 2023-12-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_prompt_delete_prompts'),
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('username', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='responses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='likes',
        ),
        migrations.AddField(
            model_name='responses',
            name='promptid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prompts.prompt'),
        ),
        migrations.AddField(
            model_name='responses',
            name='responseid',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='responses',
            name='visibility',
            field=models.TextField(default='private'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='responses',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responses.users'),
        ),
    ]
