# Generated by Django 4.2.7 on 2023-12-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_users_remove_responses_id_remove_responses_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='responseid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
