# Generated by Django 4.2.7 on 2023-12-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_prompt_delete_prompts'),
        ('responses', '0003_alter_responses_responseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date',
        ),
        migrations.AlterField(
            model_name='responses',
            name='promptid',
            field=models.ForeignKey(db_column='promptid', null=True, on_delete=django.db.models.deletion.CASCADE, to='prompts.prompt'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='userid',
            field=models.ForeignKey(db_column='userid', null=True, on_delete=django.db.models.deletion.CASCADE, to='responses.users'),
        ),
        migrations.AlterModelTable(
            name='responses',
            table='responses',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
