# Generated by Django 4.2.7 on 2023-12-06 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Friendships", "0001_initial"),
        ("responses", "0004_remove_users_date_alter_responses_promptid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "likeid",
                    models.AutoField(
                        db_column="likeid",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(db_column="date")),
            ],
            options={"db_table": "likes",},
        ),
        migrations.RemoveField(model_name="comments", name="id",),
        migrations.RemoveField(model_name="comments", name="response",),
        migrations.AddField(
            model_name="comments",
            name="commentid",
            field=models.AutoField(
                db_column="commentid",
                default=1,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comments",
            name="responseid",
            field=models.ForeignKey(
                db_column="responseid",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="responses.responses",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comments",
            name="userid",
            field=models.ForeignKey(
                db_column="userid",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Friendships.users",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comments",
            name="date",
            field=models.DateField(db_column="date"),
        ),
        migrations.AlterField(
            model_name="comments",
            name="text",
            field=models.TextField(db_column="text"),
        ),
        migrations.AlterField(
            model_name="responses",
            name="userid",
            field=models.ForeignKey(
                db_column="userid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Friendships.users",
            ),
        ),
        migrations.AlterModelTable(name="comments", table="comments",),
        migrations.DeleteModel(name="Users",),
        migrations.AddField(
            model_name="likes",
            name="responseid",
            field=models.ForeignKey(
                db_column="responseid",
                on_delete=django.db.models.deletion.CASCADE,
                to="responses.responses",
            ),
        ),
        migrations.AddField(
            model_name="likes",
            name="userid",
            field=models.ForeignKey(
                db_column="userid",
                on_delete=django.db.models.deletion.CASCADE,
                to="Friendships.users",
            ),
        ),
    ]
