# Generated by Django 4.2.7 on 2023-12-06 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_users_django_user_remove_users_id_and_more"),
        (
            "responses",
            "0005_likes_remove_comments_id_remove_comments_response_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="userid",
            field=models.ForeignKey(
                db_column="userid",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.users",
            ),
        ),
        migrations.AlterField(
            model_name="likes",
            name="userid",
            field=models.ForeignKey(
                db_column="userid",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.users",
            ),
        ),
        migrations.AlterField(
            model_name="responses",
            name="userid",
            field=models.ForeignKey(
                db_column="userid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.users",
            ),
        ),
    ]
