# Generated by Django 4.2.7 on 2023-12-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Friendships", "0003_users_alter_friendships_user1id_and_more"),
        ("responses", "0006_alter_comments_userid_alter_likes_userid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="userid",
            field=models.ForeignKey(
                db_column="userid",
                on_delete=django.db.models.deletion.CASCADE,
                to="Friendships.users",
            ),
        ),
        migrations.AlterField(
            model_name="likes",
            name="userid",
            field=models.ForeignKey(
                db_column="userid",
                on_delete=django.db.models.deletion.CASCADE,
                to="Friendships.users",
            ),
        ),
        migrations.AlterField(
            model_name="responses",
            name="userid",
            field=models.ForeignKey(
                db_column="userid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Friendships.users",
            ),
        ),
    ]
