# Generated by Django 4.1.2 on 2023-12-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_users_userid_alter_users_table"),
        ("responses", "0007_alter_comments_userid_alter_likes_userid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="userid",
            field=models.ForeignKey(
                db_column="userid",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.users",
            ),
        ),
        migrations.AlterField(
            model_name="likes",
            name="userid",
            field=models.ForeignKey(
                db_column="userid",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.users",
            ),
        ),
        migrations.AlterField(
            model_name="responses",
            name="userid",
            field=models.ForeignKey(
                db_column="userid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.users",
            ),
        ),
    ]
