# Generated by Django 4.2.7 on 2023-12-06 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0006_alter_comments_userid_alter_likes_userid_and_more"),
        ("users", "0002_remove_users_django_user_remove_users_id_and_more"),
        ("Friendships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendships",
            name="user1id",
            field=models.ForeignKey(
                db_column="user1id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_initiated",
                to="users.users",
            ),
        ),
        migrations.AlterField(
            model_name="friendships",
            name="user2id",
            field=models.ForeignKey(
                db_column="user2id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_received",
                to="users.users",
            ),
        ),
        migrations.DeleteModel(name="Users",),
    ]
