# Generated by Django 4.2.7 on 2023-12-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "Friendships",
            "0002_alter_friendships_user1id_alter_friendships_user2id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "userid",
                    models.AutoField(
                        default=0, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("username", models.TextField()),
                ("email", models.TextField()),
                ("password", models.TextField()),
            ],
            options={"db_table": "users",},
        ),
        migrations.AlterField(
            model_name="friendships",
            name="user1id",
            field=models.ForeignKey(
                db_column="user1id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_initiated",
                to="Friendships.users",
            ),
        ),
        migrations.AlterField(
            model_name="friendships",
            name="user2id",
            field=models.ForeignKey(
                db_column="user2id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_received",
                to="Friendships.users",
            ),
        ),
    ]
