# Generated by Django 4.1.2 on 2023-12-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Friendships", "0002_users_alter_friendships_user1id_and_more"),
        ("Friendships", "0003_users_alter_friendships_user1id_and_more"),
    ]

    operations = []
