# Generated by Django 4.1.2 on 2023-12-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_users_userid_alter_users_table"),
        ("responses", "0008_alter_comments_userid_alter_likes_userid_and_more"),
        ("Friendships", "0004_merge_20231206_1309"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendships",
            name="user1id",
            field=models.ForeignKey(
                db_column="user1id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_initiated",
                to="users.users",
            ),
        ),
        migrations.AlterField(
            model_name="friendships",
            name="user2id",
            field=models.ForeignKey(
                db_column="user2id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_received",
                to="users.users",
            ),
        ),
        migrations.DeleteModel(name="Users",),
    ]
